project_id = "qfaguilznugwafdfecpl"

[functions.user-management]
verify_jwt = true

[functions.course-management]
verify_jwt = false

[functions.enrollment]
verify_jwt = true

[functions.certificate-generator]
verify_jwt = true

[functions.contact-inquiry]
verify_jwt = false